---
- hosts: all
  become: yes
  tasks:
   - name: installing jenkins repo
     yum_repository:
      name: jenkins-stable
      description: epel release
      baseurl: http://pkg.jenkins.io/redhat-stable
      gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

   - name: installing java and jenkins
     yum:
      name: "{{item}}"
      state: started
    loop:
       - fontconfig
       - java-11-openjdk
       - jenkins
    notify:
     - start_again
   - name: checking status of the jenkins
     shell:
      cmd: 'sudo systemctl status jenkins -l'
      register: statusout
   - name: display
     debug:
      msg: "{{statusout}}"
  
  handlers:
   - name: start_again
     service:
      name: jenkins
      state: started